import NavBar from './components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NextJS',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      
      <body className={inter.className}>
       
        <NavBar/>
        {children}
      
      </body>
      
    </html>
  )
}
